# Generated by Django 3.1.3 on 2020-11-24 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_auto_20201124_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='datetime',
            new_name='date',
        ),
    ]
