# Generated by Django 3.1.3 on 2020-11-25 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0005_auto_20201125_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gamer',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='levelupapi.gamer'),
            preserve_default=False,
        ),
    ]
